// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "secrets.h"

void onPwrSwitchChange();
void onColourEffectsChange();

bool pwrSwitch;
int colourEffects = 255;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pwrSwitch, READWRITE, ON_CHANGE, onPwrSwitchChange);
  ArduinoCloud.addProperty(colourEffects, READWRITE, ON_CHANGE, onColourEffectsChange, 1);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
