// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "secrets.h"

void onPwrSwitchChange();

bool pwrSwitch ;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pwrSwitch, READWRITE, ON_CHANGE, onPwrSwitchChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
